/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { StackAiClient } from './StackAiClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActionDescription } from './models/ActionDescription';
export type { ActionSchema } from './models/ActionSchema';
export type { AgentBuilderRequest } from './models/AgentBuilderRequest';
export type { ApiEndpointSchema } from './models/ApiEndpointSchema';
export type { ApiResponse } from './models/ApiResponse';
export type { ApiToolInfo } from './models/ApiToolInfo';
export type { AppendMessagesBody } from './models/AppendMessagesBody';
export type { AssistantMessage_Input } from './models/AssistantMessage_Input';
export type { AssistantMessage_Output } from './models/AssistantMessage_Output';
export { Attachment } from './models/Attachment';
export type { AvailableConnection } from './models/AvailableConnection';
export type { BaseConnectionDataModel_Input } from './models/BaseConnectionDataModel_Input';
export type { BaseConnectionDataModel_Output } from './models/BaseConnectionDataModel_Output';
export type { Body_create_resource_knowledge_bases__knowledge_base_id__resources_post } from './models/Body_create_resource_knowledge_bases__knowledge_base_id__resources_post';
export type { Body_upload_documents_indexing_v0_documents__flow_id___org_id___node_id__post } from './models/Body_upload_documents_indexing_v0_documents__flow_id___org_id___node_id__post';
export type { Body_upload_to_user_bucket_documents__org_id___flow_id___node_id___user_id__post } from './models/Body_upload_to_user_bucket_documents__org_id___flow_id___node_id___user_id__post';
export type { BooleanProperty } from './models/BooleanProperty';
export type { ChatConfigurationResponse } from './models/ChatConfigurationResponse';
export type { ChatUIOptionsResponse } from './models/ChatUIOptionsResponse';
export type { CheckoutSessionCreationRequest } from './models/CheckoutSessionCreationRequest';
export type { CheckoutSessionCreationResponse } from './models/CheckoutSessionCreationResponse';
export type { ChunkerData_Input } from './models/ChunkerData_Input';
export type { ChunkerData_Output } from './models/ChunkerData_Output';
export { ChunkerType } from './models/ChunkerType';
export type { Citation_Input } from './models/Citation_Input';
export type { Citation_Output } from './models/Citation_Output';
export { CitationSourceType } from './models/CitationSourceType';
export type { Connection } from './models/Connection';
export type { ConnectionCard } from './models/ConnectionCard';
export type { ConnectionIDWrapper } from './models/ConnectionIDWrapper';
export type { ConnectionParameter } from './models/ConnectionParameter';
export type { ConnectionResourceRequestData } from './models/ConnectionResourceRequestData';
export { ConnectionType } from './models/ConnectionType';
export type { Conversation } from './models/Conversation';
export type { CreateFolderRequest } from './models/CreateFolderRequest';
export type { CreateKnowledgeBaseRequest } from './models/CreateKnowledgeBaseRequest';
export type { CreateTokenLimitRequest } from './models/CreateTokenLimitRequest';
export type { CreateToolProviderSchema } from './models/CreateToolProviderSchema';
export type { CronWebhook } from './models/CronWebhook';
export type { CursorPaginated_Union_StackFile__StackDirectory__ } from './models/CursorPaginated_Union_StackFile__StackDirectory__';
export { CustomApiHttpRequest } from './models/CustomApiHttpRequest';
export type { CustomerPortalRequest } from './models/CustomerPortalRequest';
export type { CustomerPortalResponse } from './models/CustomerPortalResponse';
export type { DateProperty } from './models/DateProperty';
export type { EmbeddingsData_Input } from './models/EmbeddingsData_Input';
export type { EmbeddingsData_Output } from './models/EmbeddingsData_Output';
export type { EnrichedChunk } from './models/EnrichedChunk';
export type { FeedbackAPIParams } from './models/FeedbackAPIParams';
export { FeedbackMessage } from './models/FeedbackMessage';
export { FeedbackType } from './models/FeedbackType';
export type { FieldNodeResponse } from './models/FieldNodeResponse';
export type { FileContentPart } from './models/FileContentPart';
export type { FileMetadata } from './models/FileMetadata';
export type { FileMetadatasResponse } from './models/FileMetadatasResponse';
export type { FileUserMetadataUpdateRequest } from './models/FileUserMetadataUpdateRequest';
export type { FlowAccessControl } from './models/FlowAccessControl';
export type { Folder } from './models/Folder';
export type { FolderQuery } from './models/FolderQuery';
export type { FolderUpdate } from './models/FolderUpdate';
export type { FormLogResponse } from './models/FormLogResponse';
export type { FormLogSummariesResponse } from './models/FormLogSummariesResponse';
export type { HeaderSchema } from './models/HeaderSchema';
export { HttpMethod } from './models/HttpMethod';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { ImageContentPart } from './models/ImageContentPart';
export type { IndexingParams_Input } from './models/IndexingParams_Input';
export type { IndexingParams_Output } from './models/IndexingParams_Output';
export type { InfinitePagination_Conversation_ } from './models/InfinitePagination_Conversation_';
export type { InfinitePagination_Union_UserMessage__AssistantMessage__ } from './models/InfinitePagination_Union_UserMessage__AssistantMessage__';
export type { Invitation } from './models/Invitation';
export type { InvitationRequest } from './models/InvitationRequest';
export type { InvitationResponse } from './models/InvitationResponse';
export type { KBMetadataSchemaResponse } from './models/KBMetadataSchemaResponse';
export type { KnowledgeBaseData } from './models/KnowledgeBaseData';
export type { KnowledgeBaseDataUpdate } from './models/KnowledgeBaseDataUpdate';
export type { KnowledgeBaseMetadataSchema } from './models/KnowledgeBaseMetadataSchema';
export type { KnowledgeBaseRBA } from './models/KnowledgeBaseRBA';
export { KnowledgeBaseRole } from './models/KnowledgeBaseRole';
export type { KnowledgeBaseStorageInfo } from './models/KnowledgeBaseStorageInfo';
export { MessageStatusType } from './models/MessageStatusType';
export type { MetadataSchema } from './models/MetadataSchema';
export type { NewMessageRequest } from './models/NewMessageRequest';
export type { NumberProperty } from './models/NumberProperty';
export { OrganizationPlanBillingPeriod } from './models/OrganizationPlanBillingPeriod';
export { OrganizationPlanEnum } from './models/OrganizationPlanEnum';
export type { OrganizationPrompt } from './models/OrganizationPrompt';
export type { OrganizationPromptCreate } from './models/OrganizationPromptCreate';
export type { OrganizationPromptUpdate } from './models/OrganizationPromptUpdate';
export type { PositionInDocument } from './models/PositionInDocument';
export type { PostgresData } from './models/PostgresData';
export { ProjectLogsBehaviour } from './models/ProjectLogsBehaviour';
export type { ProjectMetadata } from './models/ProjectMetadata';
export type { ProjectRunSummary } from './models/ProjectRunSummary';
export type { ProjectTrigger } from './models/ProjectTrigger';
export type { ProjectTriggerCreate } from './models/ProjectTriggerCreate';
export { ProjectTriggerStatus } from './models/ProjectTriggerStatus';
export { ProjectTypeEnum } from './models/ProjectTypeEnum';
export type { ProjectUpdateResult } from './models/ProjectUpdateResult';
export type { PropertyUpdate } from './models/PropertyUpdate';
export type { ProviderConnectionType } from './models/ProviderConnectionType';
export type { ProviderCredentialsOption } from './models/ProviderCredentialsOption';
export { ProviderType } from './models/ProviderType';
export type { ReloadMessageRequest } from './models/ReloadMessageRequest';
export type { RenameConversationRequest } from './models/RenameConversationRequest';
export type { ResumeRequest } from './models/ResumeRequest';
export type { Run } from './models/Run';
export type { RunFeedback } from './models/RunFeedback';
export type { ScheduledTask } from './models/ScheduledTask';
export type { SeatsUsage } from './models/SeatsUsage';
export type { SelectedTool } from './models/SelectedTool';
export type { SelectedWebsiteSource } from './models/SelectedWebsiteSource';
export type { SelectionItem } from './models/SelectionItem';
export type { StackDirectory } from './models/StackDirectory';
export type { StackFile } from './models/StackFile';
export { StackFileStatusEnum } from './models/StackFileStatusEnum';
export { StackInodeTypeEnum } from './models/StackInodeTypeEnum';
export type { StackVFSPath } from './models/StackVFSPath';
export type { StorageUsageResponse } from './models/StorageUsageResponse';
export type { StringListOption } from './models/StringListOption';
export { StringListOptionColor } from './models/StringListOptionColor';
export type { StringListProperty_Input } from './models/StringListProperty_Input';
export type { StringListProperty_Output } from './models/StringListProperty_Output';
export type { StringProperty } from './models/StringProperty';
export { StringSubtypeEnum } from './models/StringSubtypeEnum';
export type { SubscriptionDeletionRequest } from './models/SubscriptionDeletionRequest';
export { TaskType } from './models/TaskType';
export type { TaskUpdatePayload } from './models/TaskUpdatePayload';
export type { TextContentPart } from './models/TextContentPart';
export type { ToolCall } from './models/ToolCall';
export type { ToolCallContentPart_Input } from './models/ToolCallContentPart_Input';
export type { ToolCallContentPart_Output } from './models/ToolCallContentPart_Output';
export type { ToolCallContentPartStatus } from './models/ToolCallContentPartStatus';
export type { ToolConfigOption } from './models/ToolConfigOption';
export type { ToolInputParameterSchema } from './models/ToolInputParameterSchema';
export type { ToolOptionsRequest } from './models/ToolOptionsRequest';
export type { ToolOutputParameterSchema } from './models/ToolOutputParameterSchema';
export { ToolParameterType } from './models/ToolParameterType';
export type { ToolProviderSchema } from './models/ToolProviderSchema';
export type { TriggerDefinition } from './models/TriggerDefinition';
export type { TriggerSchema } from './models/TriggerSchema';
export { TriggerType } from './models/TriggerType';
export type { UIExportSecurityResponse } from './models/UIExportSecurityResponse';
export { UITypeEnum } from './models/UITypeEnum';
export { UpdateKnowledgeBaseRBACRequest } from './models/UpdateKnowledgeBaseRBACRequest';
export type { UpdateUserMetadataSchemaRequest } from './models/UpdateUserMetadataSchemaRequest';
export type { UpdateUserNotification } from './models/UpdateUserNotification';
export type { UsageLimitMetadata } from './models/UsageLimitMetadata';
export { UsageLimitType } from './models/UsageLimitType';
export type { UserMessage_Input } from './models/UserMessage_Input';
export type { UserMessage_Output } from './models/UserMessage_Output';
export type { UserProfile } from './models/UserProfile';
export type { ValidationError } from './models/ValidationError';
export { WorkflowState } from './models/WorkflowState';

export { AgentBuilderService } from './services/AgentBuilderService';
export { AnalyticsService } from './services/AnalyticsService';
export { ChatService } from './services/ChatService';
export { ConnectionsService } from './services/ConnectionsService';
export { ConversationsService } from './services/ConversationsService';
export { CustomApiService } from './services/CustomApiService';
export { CustomToolsService } from './services/CustomToolsService';
export { DefaultService } from './services/DefaultService';
export { DocumentsService } from './services/DocumentsService';
export { FoldersService } from './services/FoldersService';
export { FormService } from './services/FormService';
export { GetMetadataFromARunService } from './services/GetMetadataFromARunService';
export { IntegrationsService } from './services/IntegrationsService';
export { InvitationsService } from './services/InvitationsService';
export { KnowledgeBaseService } from './services/KnowledgeBaseService';
export { KnowledgeBasesService } from './services/KnowledgeBasesService';
export { ManagerService } from './services/ManagerService';
export { MessagesService } from './services/MessagesService';
export { NotificationsService } from './services/NotificationsService';
export { OauthService } from './services/OauthService';
export { OrganizationPromptsService } from './services/OrganizationPromptsService';
export { ResourcesService } from './services/ResourcesService';
export { RunFlowService } from './services/RunFlowService';
export { StackaiToolsService } from './services/StackaiToolsService';
export { StorageService } from './services/StorageService';
export { StripeService } from './services/StripeService';
export { TasksService } from './services/TasksService';
export { TokenLimitsService } from './services/TokenLimitsService';
export { ToolsService } from './services/ToolsService';
export { TriggersService } from './services/TriggersService';
export { V2Service } from './services/V2Service';
export { WorkflowService } from './services/WorkflowService';
